version: '2'

networks:
    platypus:
        external: true

services:
    golang:
        image: development/go
        networks:
            - platypus
        ports:
            - "3001:80"
        volumes:
            - ..:/app
        environment:
            - PROJECT=bitbucket.com/dkfbasel/development/test
            - DIRECTORY=src/server
            - IGNORE=/src/web
            - ARGUMENTS=-test=something

    webpack:
        image: development/webpack
        depends_on:
            - golang
        networks:
            - platypus
        ports:
            - "3000:3000"
        volumes:
            - ..:/app
        environment:
            - DIRECTORY=src/web
            - COMMAND=npm run dev
